### ISSUE TITLE
Bundle Analyser is not working

### ISSUE THREAD

**Issue by agubler** [dojo/cli-build-app#51] opened 2018-01-31 09:41 UTC
The bundles analyser output in the `info` directory is not working. The pages are throwing errors when they are opened.

**Comment by maier49** [comment] 2018-03-19 16:01
The previous version of the analyzer is not working either, but the latest version of the original analyzer is. There's been some updates to the bundle parsing code as well as throughout the rest of the analyzer. We'll probably pull those updates in and release a new version of the bundle analyzer.

**Comment by maier49** [comment] 2018-03-27 20:22
I've addressed the originally reported issue by pulling in changes from the original webpack-bundle-analyzer repo, and also addressed some style issues caused by our now much longer bundle names and filenames. These updates are in a PR [here](https://github.com/bitpshr/webpack-bundle-analyzer/pull/5).

However, currently the build is terminating the process explicitly to avoid the build time rendering from hanging. This prevents the bundle analyzer from ever running, so even if we include the fixes in that PR we won't be getting any reports unless we deal with the BTR issues in some other fashion.

We discussed moving this into @dojo/webpack-contrib, but I'm concerned this might be a wasted effort. Whenever 3.0.0 of the original analyzer lands it's going to change the architecture, and may also eliminate the need for us to fork. Reworking this entire project's build process only to potentially need to do the same for 3.0.0, or for it to be largely unnecessary with the new architecture.  Thoughts on that @agubler @matt-gadd ?

**Comment by maier49** [comment] 2018-03-29 13:09
The way the analyzer was running was, based on the comments in the code, only to make sure the logs were at the end of the build. I've updated the PR to just run it sync, avoiding the issue where it is terminated by call to `process.exit(0)` in `cli-build-app`, and verified that it still works.

**Comment by maier49** [comment] 2018-05-01 14:39
We'll need to either fork our analyzer repo or migrate this to webpack-contrib, since the PR is unlikely to be merged anytime soon.

**Closed** 2018-09-13 18:32 UTC
Labels: bug
